server:
  port: 8080

reCaptcha:
  secretKey: ${CAPTCHA_SECRET}

jwt:
  secretKey: ${JWT_SECRET}
  expiredMs: 3600000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  application:
    name: operation
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development, 'none' or 'validate' for production
    show-sql: true # Set to false for production
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-southeast-2