apiVersion: v1
kind: Service
metadata:
  name: operation
  labels:
    app: operation
spec:
  selector:
    app: operation
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
